coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        flags:
          - unit
        paths:
          - "core/src"
          - "common/src"
          - "viz/src"
    patch:
      default:
        target: 80%
        flags:
          - unit
        paths:
          - "core/src"
          - "common/src"
          - "viz/src"
        only_pulls: true

flag_management:
  default_rules:
    carryforward: true
