name: CD - Documentation
run-name: CD - Documentation (#${{ github.run_number }})

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main

concurrency:
  group: cd-docs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy to GitHub pages
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: web-docs/yarn.lock

      - name: Install dependencies
        run: cd web-docs && yarn install

      - name: Build website
        run: cd web-docs && yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-docs/build
